### ISSUE TITLE
BUG: Changing font size and editor theme doesn't work

### ISSUE THREAD

**Issue by superDuperCyberTechno** [dbgate/dbgate#244]
**Describe the bug**
When I change the editor theme or the font size, nothing happens. As far as I can remember, changing the editor theme worked as it should in the prior version.

**To Reproduce**
Open Settings->Themes and change the editor theme or font size.

**Expected behavior**
The theme and font size should change accordingly.

**Screenshots**
N/A

**Version Information (please complete the following information):**
 - OS: Ubuntu 20.04
 - App Version: 4.7.2 
 - Install source: Snap
 - Type: Desktop client
 - Database engine: PostgreSQL

**Comment by janproch** [comment]
Thanks, good catch. Probably I will create hotfix release tomorrow

**Comment by superDuperCyberTechno** [comment]
Did you ghostfix this already? It works fine now. Still v4.7.2.

**Comment by janproch** [comment]
No, I have not fixed it. I tried to fix it today, but I was unable to reproduce it, although I have reproduced it when you created this issue.

Probably it occurs under some strange conditions, if this problem will still occur, please let me know.

**Comment by superDuperCyberTechno** [comment]
I just suspected you did a fix but didn't bump the version number or something. Anyway, I'll keep an eye on it.

**Comment by superDuperCyberTechno** [comment]
After some usage, the font has reverted back to the original size and changing it doesn't work. Changing the theme doesn't work either. This is on v4.7.3.

**Comment by janproch** [comment]
@superDuperCyberTechno if you run dbgate from console, are there any errors when changing font size or theme?

When you are in this incorrect state, when chaging font size doesn't work. does work saving new connection (or editing existing) ?

Maybe it could be related to https://github.com/dbgate/dbgate/issues/248 . This configuration is stored in dbgate-data/settings.json file

**Comment by superDuperCyberTechno** [comment]
It seems to happen very erratically. Running `dbgate` from the terminal yields the following error on startup:
```
(dbgate:26249): Gtk-WARNING **: 11:54:22.751: Theme parsing error: gtk.css:1418:23: 'font-feature-settings' is not a valid property name
```
That error message however, does not seem to interact with the error we are discussing here.

---

When I close DbGate, sometimes it returns this error in the terminal:
```
Error [ERR_IPC_CHANNEL_CLOSED]: Channel closed
    at process.target.send (internal/child_process.js:705:16)
    at Timeout._onTimeout (/snap/dbgate/229/resources/app.asar/packages/api/dist/bundle.js:21:2007)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
Emitted 'error' event on process instance at:
    at internal/child_process.js:709:35
    at processTicksAndRejections (internal/process/task_queues.js:75:11) {
  code: 'ERR_IPC_CHANNEL_CLOSED'
}
```
After this error happens, it doesn't exit the process. It just halts the terminal. However, in this state the `dbgate` process is not present on my system anymore. Ctrl-C gets me control back to the terminal.

**Comment by janproch** [comment]
I have replicated this behaviour after installing new plugin. I am not sure, if it was your case, but this scenario I fixed now (will be released in BETA today)

**Comment by superDuperCyberTechno** [comment]
Alright, good to hear. I haven't dabbled in plugins but I _do_ use PostgreSQL exclusively and that functionality is listed in the plugins section...?

**Comment by janproch** [comment]
It was caused by repeated initialization, after this operation app was partially "detached" from main process, one of possible causes was installing new plugin.

I am closing it for now, if you will see this problem again, please reopen this issue. 

Fix was released in 4.8.3

**Comment by superDuperCyberTechno** [comment]
This bug is still lurking. Just made a clean install of Ubuntu 22.04 and installed DbGate via Snap.
